In [1]:
import numpy as np

In [2]:
X=np.array([1,3,4,5,np.nan,55])

In [3]:
X

array([ 1.,  3.,  4.,  5., nan, 55.])

In [4]:
X.mean()

nan

In [5]:
X.sum()

nan

In [6]:
b=np.array([1,2,3,np.inf,np.nan,None,53])

In [7]:
b

array([1, 2, 3, inf, nan, None, 53], dtype=object)

In [10]:
np.isnan(np.nan)

True

In [11]:
np.isinf(np.inf)

True

In [14]:
np.isfinite(np.inf), np.isfinite(np.nan)

(False, False)

In [16]:
np.isnan(X)

array([False, False, False, False,  True, False])

In [17]:
np.isinf(X)

array([False, False, False, False, False, False])

In [18]:
np.isfinite(X)

array([ True,  True,  True,  True, False,  True])

In [19]:
a=np.array([1,2,3,np.nan,np.nan,8])

In [21]:
a[~np.isnan(a)]

array([1., 2., 3., 8.])

In [22]:
a[np.isnan(a)] 
#equivalent to np.isfinite(a)

array([nan, nan])

In [23]:
a[np.isfinite(a)].sum()

14.0

In [24]:
a[np.isfinite(a)].mean()

3.5

In [25]:
import pandas as pd

In [26]:
#pandas utitlity
#checking null
pd.isnull(np.nan)

True

In [27]:
pd.isna(None)

True

In [28]:
pd.notnull(np.nan)

False

In [29]:
pd.notna(None)

False

In [30]:
pd.notnull(3)

True

In [31]:
pd.isna(3)

False

In [32]:
#this na/null functions also work with series and data frames
pd.isnull(pd.Series([1,2,np.nan,7]))

0    False
1    False
2     True
3    False
dtype: bool

In [33]:
pd.notnull(pd.Series([1,2,np.nan,7]))

0     True
1     True
2    False
3     True
dtype: bool

In [34]:
pd.isnull(pd.DataFrame({
    'column A':[1,2,np.nan],
    'column B':[1,np.nan,np.nan],
    'column C':[np.nan,np.nan,np.nan],
    
}))

column A  column B  column C
0     False     False      True
1     False      True      True
2      True      True      True

In [35]:
#operations with pandas series, it just ignores them as opposed to numpy
pd.Series([1,2,3,np.nan]).sum()

6.0

In [36]:
pd.Series([1,2,np.nan,np.nan,5]).mean()

2.6666666666666665

In [37]:
pd.Series([1,2,3,np.nan]).count()

3

In [38]:
s=pd.Series([1,2,4,np.nan,np.nan,53])

In [39]:
pd.isnull(s)

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

In [40]:
pd.notnull(s)

0     True
1     True
2     True
3    False
4    False
5     True
dtype: bool

In [41]:
pd.notnull(s).sum()

4

In [42]:
pd.isnull(s).sum()

2

In [43]:
s[pd.notnull(s)]

0     1.0
1     2.0
2     4.0
5    53.0
dtype: float64

In [44]:
s[pd.notnull(s)].sum()

60.0

In [45]:
s[pd.isna(s)]

3   NaN
4   NaN
dtype: float64

In [46]:
s[pd.isna(s)].mean()

nan

In [47]:
#both notnull and isnull are methods of DataFrame and Series
s[s.notnull()]

0     1.0
1     2.0
2     4.0
5    53.0
dtype: float64

In [48]:
s

0     1.0
1     2.0
2     4.0
3     NaN
4     NaN
5    53.0
dtype: float64

In [49]:
s.dropna()

0     1.0
1     2.0
2     4.0
5    53.0
dtype: float64

In [62]:
#dropping null in series is easier as we have seen compared to dataframes

df=pd.DataFrame({
    'Column A':[1,2,3,np.nan,np.nan],
    'Column B':[2,3,np.nan,np.nan,np.nan],
    'Column C':[12,4,9,34,90],
    'Column D':[3,np.nan,4,np.nan,54]
})

In [63]:
df

Column A  Column B  Column C  Column D
0       1.0       2.0        12       3.0
1       2.0       3.0         4       NaN
2       3.0       NaN         9       4.0
3       NaN       NaN        34       NaN
4       NaN       NaN        90      54.0

In [64]:
df.shape

(5, 4)

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
Column A    3 non-null float64
Column B    2 non-null float64
Column C    5 non-null int64
Column D    3 non-null float64
dtypes: float64(3), int64(1)
memory usage: 288.0 bytes


In [66]:
df.isnull()

Column A  Column B  Column C  Column D
0     False     False     False     False
1     False     False     False      True
2     False      True     False     False
3      True      True     False      True
4      True      True     False     False

In [67]:
df.isnull().sum()

Column A    2
Column B    3
Column C    0
Column D    2
dtype: int64

In [68]:
df.isnull().count()

Column A    5
Column B    5
Column C    5
Column D    5
dtype: int64

In [69]:
df.notnull()

Column A  Column B  Column C  Column D
0      True      True      True      True
1      True      True      True     False
2      True     False      True      True
3     False     False      True     False
4     False     False      True      True

In [70]:
df.notnull().sum()

Column A    3
Column B    2
Column C    5
Column D    3
dtype: int64

In [71]:
df.dropna()

Column A  Column B  Column C  Column D
0       1.0       2.0        12       3.0

In [72]:
#drops the rows of the dataframe
df.dropna(axis=0)

Column A  Column B  Column C  Column D
0       1.0       2.0        12       3.0

In [75]:
#drops columns of the dataframe
df.dropna(axis=1)

Column C
0        12
1         4
2         9
3        34
4        90

In [76]:
df.dropna(axis=1).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 1 columns):
Column C    5 non-null int64
dtypes: int64(1)
memory usage: 168.0 bytes


In [94]:
'''dropping drops the columns and rows with at least any non null value, which can be depending on the case, too extreme. we can control
this behavior with the how parameter, can be either how or any '''

'dropping drops the columns and rows with at least any non null value, which can be depending on the case, too extreme. we can control\nthis behavior with the how parameter, can be either how or any '

In [77]:
df2=pd.DataFrame({
    'Column A':[1,2,3],
    'Column B':[3,np.nan,5],
    'Column C':[2,np.nan,np.nan]
})

In [78]:
df2

Column A  Column B  Column C
0         1       3.0       2.0
1         2       NaN       NaN
2         3       5.0       NaN

In [79]:
df2.dropna(how="all")
"""drops rows where all entries are null"""

Column A  Column B  Column C
0         1       3.0       2.0
1         2       NaN       NaN
2         3       5.0       NaN

In [80]:
df2.dropna(how="any")

Column A  Column B  Column C
0         1       3.0       2.0

In [81]:
df2.dropna(how="all",axis=1)

Column A  Column B  Column C
0         1       3.0       2.0
1         2       NaN       NaN
2         3       5.0       NaN

In [82]:
df2.dropna(how="any",axis=1)

Column A
0         1
1         2
2         3

In [83]:
#use thresh=minimum no of non-null values
df2.dropna(thresh=2)

Column A  Column B  Column C
0         1       3.0       2.0
2         3       5.0       NaN

In [84]:
df.dropna(thresh=2)

Column A  Column B  Column C  Column D
0       1.0       2.0        12       3.0
1       2.0       3.0         4       NaN
2       3.0       NaN         9       4.0
4       NaN       NaN        90      54.0

In [85]:
df.dropna(thresh=3)

Column A  Column B  Column C  Column D
0       1.0       2.0        12       3.0
1       2.0       3.0         4       NaN
2       3.0       NaN         9       4.0

In [86]:
df.dropna(thresh=3,axis=1)

Column A  Column C  Column D
0       1.0        12       3.0
1       2.0         4       NaN
2       3.0         9       4.0
3       NaN        34       NaN
4       NaN        90      54.0

In [87]:
s

0     1.0
1     2.0
2     4.0
3     NaN
4     NaN
5    53.0
dtype: float64

In [88]:
s.fillna(0)

0     1.0
1     2.0
2     4.0
3     0.0
4     0.0
5    53.0
dtype: float64

In [89]:
s.fillna(3)

0     1.0
1     2.0
2     4.0
3     3.0
4     3.0
5    53.0
dtype: float64

In [90]:
s.fillna(s.mean())

0     1.0
1     2.0
2     4.0
3    15.0
4    15.0
5    53.0
dtype: float64

In [91]:
s.fillna(method="ffill")

0     1.0
1     2.0
2     4.0
3     4.0
4     4.0
5    53.0
dtype: float64

In [92]:
s.fillna(method="bfill")

0     1.0
1     2.0
2     4.0
3    53.0
4    53.0
5    53.0
dtype: float64

In [93]:
"""However, this can still leave non-null values at the extremes of the DataFrame/series """

'However, this can still leave non-null values at the extremes of the DataFrame/series '

In [95]:
#dropna can be used as well on DataFrames and here you have more control
df

Column A  Column B  Column C  Column D
0       1.0       2.0        12       3.0
1       2.0       3.0         4       NaN
2       3.0       NaN         9       4.0
3       NaN       NaN        34       NaN
4       NaN       NaN        90      54.0

In [98]:
df.fillna({'Column A':4,'Column B':10,'Column D':df['Column D'].mean()})

Column A  Column B  Column C   Column D
0       1.0       2.0        12   3.000000
1       2.0       3.0         4  20.333333
2       3.0      10.0         9   4.000000
3       4.0      10.0        34  20.333333
4       4.0      10.0        90  54.000000

In [99]:
df.fillna(method="ffill")

Column A  Column B  Column C  Column D
0       1.0       2.0        12       3.0
1       2.0       3.0         4       3.0
2       3.0       3.0         9       4.0
3       3.0       3.0        34       4.0
4       3.0       3.0        90      54.0

In [101]:
df.fillna(method="ffill",axis=1)

Column A  Column B  Column C  Column D
0       1.0       2.0      12.0       3.0
1       2.0       3.0       4.0       4.0
2       3.0       3.0       9.0       4.0
3       NaN       NaN      34.0      34.0
4       NaN       NaN      90.0      54.0

In [102]:
df.fillna(method='ffill',axis=0)

Column A  Column B  Column C  Column D
0       1.0       2.0        12       3.0
1       2.0       3.0         4       3.0
2       3.0       3.0         9       4.0
3       3.0       3.0        34       4.0
4       3.0       3.0        90      54.0

In [106]:
df.fillna(method='bfill',axis=1)

Column A  Column B  Column C  Column D
0       1.0       2.0      12.0       3.0
1       2.0       3.0       4.0       NaN
2       3.0       9.0       9.0       4.0
3      34.0      34.0      34.0       NaN
4      90.0      90.0      90.0      54.0

In [112]:
#length of dropna is less than actual element
len(s)

6

In [111]:
len(s.dropna())

4

In [113]:
#excludes nan from its results
s.count()

4

In [116]:
s.isnull().all()

False

In [121]:
pd.Series([1, 2]).notnull().all()

True

In [123]:
s.notnull().values.any()

True

In [126]:
s.isnull().values

array([False, False, False,  True,  True, False])

In [127]:
s.isnull().values.all()

False