In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.16.5


In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.random.randint(10,50,20)

array([34, 21, 40, 15, 19, 29, 31, 45, 25, 11, 37, 39, 19, 39, 25, 23, 15,
       49, 31, 13])

In [6]:
np.random.randint?

In [7]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [11]:
np.ones((3,2), dtype=np.float64)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
np.ones?

In [12]:
X=np.arange(4, dtype=np.int)
X

array([0, 1, 2, 3])

In [13]:
np.ones_like(X)

array([1, 1, 1, 1])

In [14]:
X=np.array([[1,2,4], [4,5,6]], dtype=np.int)
X

array([[1, 2, 4],
       [4, 5, 6]])

In [15]:
np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

In [18]:
#Matrix of 4x4 filled with 5's
np.ones([4,4],dtype=np.int)*5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [23]:
#new matrix as X filled with 7's
X=np.array([[2,4],[3,6]], dtype=np.int)

np.ones_like(X)*7

array([[7, 7],
       [7, 7]])

In [24]:
#new identity matrix with 3 1's on diagonal and zeros elsewhere
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.random.randint(1,10,3)

array([9, 5, 7])

In [33]:
np.random.randn(3,3,3)

array([[[-1.42157306, -0.7290566 , -0.32912291],
        [-0.53436312,  0.08191201,  1.93824733],
        [-0.34273838,  0.07170013, -0.95726284]],

       [[ 0.38262642,  0.32748652,  0.77559509],
        [-0.13782857,  2.12509705,  0.12582004],
        [ 1.61779286, -0.04208261, -1.29509532]],

       [[-0.23586102, -0.88480112, -0.58215626],
        [-0.58274208, -0.92881123,  1.13597643],
        [ 0.07226015, -0.60992868,  0.46745234]]])

In [37]:
X=[1,2,3]
print(X, type(X))

[1, 2, 3] <class 'list'>


In [38]:
Y=np.array(X)
type(Y)

numpy.ndarray

In [43]:
#Make a copy of numpy array and store it on Y
X=np.array([1,2,4])
print(X, id(X))
Y=np.copy(X)

[1 2 4] 1874270592176


In [42]:
print(Y,id(Y))

[1 2 4] 1874270589456


In [46]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
X=np.arange(1,11)

In [69]:
X[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [64]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [70]:
#Matrix of 3,3 filled with values from 0 to 8
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [75]:
Z=np.zeros((10,10))


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [78]:
print("%d bytes " % (Z.size* Z.itemsize))

800 bytes 


In [80]:
X=np.arange(9)

In [81]:
X[0]

0

In [82]:
X[-1]

8

In [83]:
X[[0,1,2]]

array([0, 1, 2])

In [84]:
X[1:-1]

array([1, 2, 3, 4, 5, 6, 7])

In [85]:
X[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

In [87]:
X[(X%2 != 0)]

array([1, 3, 5, 7])

In [88]:
X[::2]

array([0, 2, 4, 6, 8])

In [90]:
X[::]

array([0, 3, 6])

In [91]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[0]

array([1, 2, 3, 4])

In [92]:
X[-1]

array([13, 14, 15, 16])

In [95]:
X[0][0]

1

In [96]:
X[-1,-1]

16

In [98]:
X[1:-1,1:-1]

array([[ 6,  7],
       [10, 11]])

In [99]:
#first two elements on the first two rows
X[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [100]:
#last two elements on the last two rows
X[2:,2:]

array([[11, 12],
       [15, 16]])

In [101]:
#convert given array to float
X=[-1,2,3,-9,9]

np.array(X,np.float)

array([-1.,  2.,  3., -9.,  9.])

In [103]:
X[::-1]

[9, -9, 3, 2, -1]

In [104]:
X=np.sort(X)

In [105]:
X

array([-9, -1,  2,  3,  9])

In [113]:
Y=[0,-23,4,5,6,68,-9,12]
np.sort(Y)



array([-23,  -9,   0,   4,   5,   6,  12,  68])

In [114]:
Y[4]=100
Y

[0, -23, 4, 5, 100, 68, -9, 12]

In [128]:
X=np.arange(9).reshape(3,3)

In [129]:
X

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [130]:
#Accessing rows
X[-1]=1

In [131]:
X

array([[0, 1, 2],
       [3, 4, 5],
       [1, 1, 1]])

In [141]:
#accessing columns
X[:,2:]=0
X

array([[0, 1, 0],
       [3, 4, 0],
       [1, 1, 0]])

In [143]:
X[-1,-1]=1

In [144]:
X

array([[0, 1, 0],
       [3, 4, 0],
       [1, 1, 1]])

In [145]:
X+5

array([[5, 6, 5],
       [8, 9, 5],
       [6, 6, 6]])

In [146]:
Y

[0, -23, 4, 5, 100, 68, -9, 12]

In [150]:
np.array(Y)

array([  0, -23,   4,   5, 100,  68,  -9,  12])

In [155]:
X=np.array([0,-12,-3,-492,-9,234,5,6,3])


In [156]:
X<=0

array([ True,  True,  True,  True,  True, False, False, False, False])

In [157]:
X[(X<=0)]

array([   0,  -12,   -3, -492,   -9])

In [160]:
X[X>np.mean(X)]

array([  0, -12,  -3,  -9, 234,   5,   6,   3])

In [161]:
np.mean(X)

-29.77777777777778

In [162]:
X.mean()

-29.77777777777778

In [164]:
X.std()

179.2402346807074

In [167]:
X[(X==3)| (X==234)]

array([234,   3])

In [177]:
X.all()

False

In [178]:
X.any()

True

In [179]:
X.sum()

-268

In [180]:
X.mean()

-29.77777777777778

In [183]:
X=np.random.randint(100,size=(4,5))

In [184]:
X

array([[87, 40, 27, 74,  0],
       [33, 78,  1, 27, 28],
       [59, 27, 90, 57,  3],
       [85, 15, 19, 68, 26]])

In [185]:
#sum of columns
X.sum(axis=0)

array([264, 160, 137, 226,  57])

In [186]:
#sum of rows
X.sum(axis=1)

array([228, 167, 236, 213])

In [187]:
#mean value of its rows
X.mean(axis=1)

array([45.6, 33.4, 47.2, 42.6])

In [188]:
#mean value of columns
X.mean(axis=0)

array([66.  , 40.  , 34.25, 56.5 , 14.25])

In [189]:
X.max()

90

In [1]:
import numpy as np

In [2]:
X=np.array([1,2,4,np.nan,np.nan,4])

In [3]:
X

array([ 1.,  2.,  4., nan, nan,  4.])